import {courseSample} from './starter-samples';
import {courseChoices,windDirectionChoices,type RaceSettings} from './race-settings';
import {buildPreviewLayout} from './preview-layout';
import {PreviewWater} from './preview-water';
import type {CoursePoint} from './protocol';
/** Course-choice diagrams share native samples; glyphs and callouts stay in water. */
export class CoursePreview {
 private domains=new WeakMap<object,PreviewWater>();private measure:CanvasRenderingContext2D;
 lastLayout?:ReturnType<typeof buildPreviewLayout>;
 constructor(private element:HTMLElement){this.measure=document.createElement('canvas').getContext('2d')!;this.measure.font='11px "IBM Plex Sans"';}
 update(settings:RaceSettings){
  const area=settings.area??32799,sample=courseSample(settings.course,area,settings.windDirection);let water=this.domains.get(sample.terrain);if(!water){water=new PreviewWater(sample.terrain);this.domains.set(sample.terrain,water);}
  const layout=buildPreviewLayout(sample,settings,water,text=>this.measure.measureText(text).width);this.lastLayout=layout;
  const {project,roundings,anchors,sequence,labels}=layout,pair=(p:CoursePoint)=>{const q=project(p);return q.x.toFixed(2)+','+q.y.toFixed(2);};let land='',mask='<rect width="480" height="190" fill="white"/>';
  for(const polygon of sample.terrain.polygons){const path=polygon.points.map((p,i)=>(i?'L':'M')+pair(p)).join(' ')+' Z',d=(polygon.landInside?'':'M0 0 H480 V190 H0 Z ')+path;land+=`<path d="${d}" fill-rule="evenodd" fill="#91ac78" stroke="#718c59" stroke-width="1"/>`;mask+=`<path d="${d}" fill-rule="evenodd" fill="black"/>`;}
  const segments=layout.segments.map(({a,b})=>{const p=project(a),q=project(b);return `<path class="course-route" d="M ${pair(a)} L ${pair(b)}" stroke="#315e78" stroke-width="1.5" fill="none"/><path d="M ${pair(a)} L ${(p.x+q.x)/2} ${(p.y+q.y)/2}" marker-end="url(#course-arrow)" stroke="#315e78" stroke-width="1.5"/>`;}).join('');
  const start=`<path class="course-start" d="M ${pair(layout.startLine.a)} L ${pair(layout.startLine.b)}" stroke="#568f85" stroke-width="2.5" stroke-dasharray="3 2"/>`,finish=`<path class="course-finish" d="M ${pair(layout.finishLine.a)} L ${pair(layout.finishLine.b)}" stroke="#a57829" stroke-width="2" stroke-dasharray="3 2" stroke-dashoffset="3"/>`;
  const dots=layout.symbols.filter(s=>s.key!=='S'&&s.key!=='F').map(symbol=>{const p=project(symbol.point);return `<circle class="course-mark" cx="${p.x}" cy="${p.y}" r="${symbol.radius}" fill="#e6ab46" stroke="#8e642b" stroke-width="${Math.min(.6,symbol.radius*.25)}"/>`;}).join('');
  const callouts=labels.map(label=>{const p=project(label.anchor);return `<path d="M ${p.x} ${p.y} L ${label.leader.x} ${label.leader.y}" stroke="#315e78" stroke-width=".6" opacity=".6"/><text class="course-label" x="${label.x+3}" y="${label.y+11}">${label.text}</text>`;}).join('');
  this.element.dataset.windDirection=settings.windDirection===undefined?'auto':String(settings.windDirection);this.element.dataset.course=String(settings.course);this.element.dataset.area=String(area);this.element.dataset.short=String(!!settings.short);this.element.dataset.gate=String(!!settings.gate);this.element.dataset.missingLinks=String(layout.missingLinks);
  const repeated=[2,4,7].includes(settings.course),windLabel=settings.windDirection===undefined?'↑ Wind':'Wind from '+windDirectionChoices.find(d=>d.value===settings.windDirection)!.label,routeText=['Start',...sequence.map(key=>key==='W'?'1 Windward':key==='R'?'2 Reach':settings.gate?'3 Gate':'3 Leeward'),'Finish'].join(' → ');
  this.element.innerHTML=`<div class="course-preview-title"><strong>${courseChoices.find(c=>c.value===settings.course)!.label}</strong><span>Course sample</span></div><svg viewBox="0 0 480 190" role="img" aria-label="${routeText}" xmlns="http://www.w3.org/2000/svg"><defs><marker id="course-arrow" markerWidth="4" markerHeight="4" refX="3" refY="2" orient="auto"><path d="M0 0 L4 2 L0 4" fill="#315e78"/></marker><clipPath id="course-clip"><rect width="480" height="190" rx="6"/></clipPath><mask id="course-water" maskUnits="userSpaceOnUse" x="0" y="0" width="480" height="190">${mask}</mask></defs><g clip-path="url(#course-clip)"><rect width="480" height="190" fill="#e0edf0"/>${land}<g font-family="IBM Plex Sans,sans-serif" font-size="11" fill="#163f57" mask="url(#course-water)">${segments}${start}${finish}${dots}${callouts}</g><g font-family="IBM Plex Sans,sans-serif" font-size="11" fill="#163f57"><text x="18" y="24">${windLabel}</text>${settings.windDirection===undefined?'':'<text x="462" y="24" text-anchor="end">N ↑</text>'}${repeated?'<text x="18" y="44" font-weight="600">2 laps</text>':settings.course===5?'<text x="18" y="44">Triangle + W/L</text>':''}<text x="462" y="177" text-anchor="end">${settings.short?'Short course · ':''}Not to scale</text></g></g></svg><p class="course-preview-route">${routeText}</p>`;
 }
}
