import type {CoursePoint} from './protocol';
export interface NativeTerrain {polygons:{landInside:boolean;points:CoursePoint[]}[];venue:number;area:number;landmarks?:{kind:'lighthouse';x:number;y:number}[]}
/** Read-only geometry already generated by the native configuration. No trig,
 * random draws, raster sampling or new physics are performed here. */
export function readNativeTerrain(memory:{readI32:(a:number)=>number}):NativeTerrain {
 const i=(a:number)=>memory.readI32(a),venue=i(0x4da1f8),area=i(0x4da19c),polygons:NativeTerrain['polygons']=[];
 const contour=(x:number,y:number,count:number)=>Array.from({length:count},(_,n)=>({x:i(x+n*4),y:i(y+n*4)}));
 // Background venue points are sampling/backdrop features, not additional
 // navigable land unless the native spatial sampler enables that background.
 if(venue){const count=i(0x522f08)+i(0x511374)+(i(0x5364b0)===1?i(0x535e3c):0);if(count<0||count>37)throw Error('Unreviewed native terrain count');for(let n=1;n<=count;n++)polygons.push({landInside:true,points:contour(0x4f1cf8+n*0x124,0x4f8ee8+n*0x124,72)});}
 else{const advanced=i(0x4f69b8)>1,shoreline=i(0x50040c)===1&&!advanced;polygons.push({landInside:shoreline||i(0x4f8b78)===1,points:contour(0x4fb6b8,0x4fbc38,advanced?180:shoreline?38:36)});}
 return {polygons,venue,area,landmarks:venue?[]:[{kind:'lighthouse',x:i(0x52317c),y:i(0x535f64)}]};
}
