import type {NativeVisualPacket} from './native-visuals';
import type {ContactSummary} from './contact-world';
export interface BoatView {id:number;name:string;x:number;y:number;heading:number;speed:number;leg:number;finished:number;dnf?:boolean;status:number;penaltyClock?:number;finishTime:number;points:number[];windFrom:number;windAngle:number;luff:number;boomAngle:number;tack:number;depth?:number;groundingDepth?:number;trueWind?:number;currentSpeed?:number;currentDirection?:number;grounded?:boolean}
export interface NativeView {lookDegrees:number;lookMode:number;viewpoint:number;automatic:boolean;otherBoat:number;tacticalZoom:number;tacticalOrientation:number}
export interface CoursePoint {x:number;y:number}
export interface CourseLine {a:CoursePoint;b:CoursePoint}
export interface CourseGuide {point:number;type:number;x:number;y:number;bearing:number}
export interface NativeCourse {marks:CoursePoint[];gate?:CoursePoint[];start:CourseLine;finish:CourseLine;committee:CoursePoint&{heading:number};target:CoursePoint;navigationTarget?:CoursePoint&{point:number;finish:boolean};closeAngle:number;downwindAngle:number;showLaylines:boolean;showMarkLines:boolean;length:number;guides?:CourseGuide[];headingReference?:number;targetBearing?:number;targetDistance?:number}
export interface SceneSnapshot {contacts?:ContactSummary;nativeVisuals:NativeVisualPacket;environment?:{waves:number;currentEffect:number;gusts:{x:number;y:number;width:number;strength:number}[]};generation:number;sequence:number;time:number;clock:number;pace:number;windDirection:number;windStrength:number;boats:BoatView[];view:NativeView;panel:string|null;sheet:number;sailShape:number;spinnaker:boolean;frozen:boolean;marks:CoursePoint[];course:NativeCourse;configuration:{speed:number;course:number;wind:number;windDirection?:number;fleet:number;selector:number;area:number;venue:number;mode:number;gate:boolean;short:boolean};raceWindow?:{firstFinish?:number;deadline?:number;remaining?:number;closedByCutoff:boolean};results:boolean;resultsReady:boolean;completedRaces:number;seriesScoring:boolean;workMs:number;minimumDelayMs:number;sentAt:number}
export interface Boundary {contract?:'independent-v1';waveRngState?:number;stringsSha256?:string;frame:number;time:number;clock:number;rngState:number;memorySha256:string;shore:{previousX:number;previousTreeY:number;completedCalls:number}}
export const commands={port:32842,starboard:32841,tack:32846,close:32843,reach:32849,run:32848,jibe:32847} as const;
